[package]
name = "hello-world"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "hello-world"

[dependencies]
hyper = "0.13"
pretty_env_logger = ""
tokio = { version = "0.2", features = ["full"] }